on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0,15,30,45 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    timeout-minutes: 5

    container:
      image: ${{ matrix.image }}
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.READ_PACKAGES_TOKEN }}

    strategy:
      matrix:
        image: ["ghcr.io/jcansdale/gpr", "ghcr.io/dribbble/dribbble:ci-1.0"]
        try: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32]
    
    steps:
      - run: echo "Hello, World!"

